convolution_layer:
# first convolution layer
- in_channels:  1
  out_channels: 20
  kernel_size:  5
  stride:       1
  padding:      2

# second convolution layer
- in_channels:  20
  out_channels: 50
  kernel_size:  5
  stride:       1
  padding:      2

fully_connected_layer:
# first fully connected layer
- in_features:  2450
  out_features: 500

# second fully connected layer
- in_features:  500
  out_features: 10